//collection of the all action types, used for better code consistency
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const CHANGE_MATERIAL = 'CHANGE_MATERIAL';
export const CHANGE_PLATFORM = 'CHANGE_PLATFORM';

//LOGIN
export const AUTOLOGIN_DONE = 'AUTOLOGIN_DONE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_STATUSES = 'SET_USER_STATUSES';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';
export const ADD_LISTENER = 'ADD_LISTENER';
export const REMOVE_LISTENERS = 'REMOVE_LISTENERS';

//STORAGE
export const STORAGE_SET_COMPANIES = 'STORAGE_SET_COMPANIES';
export const STORAGE_COMPANIES_ACTIVE = 'STORAGE_COMPANIES_ACTIVE';

export const STORAGE_SET_HELP_FILTERS = 'STORAGE_SET_HELP_FILTERS';
export const STORAGE_HELP_FILTERS_ACTIVE = 'STORAGE_HELP_FILTERS_ACTIVE';

export const STORAGE_SET_HELP_MILESTONES = 'STORAGE_SET_HELP_MILESTONES';
export const STORAGE_HELP_MILESTONES_ACTIVE = 'STORAGE_HELP_MILESTONES_ACTIVE';

export const STORAGE_SET_HELP_PRICELISTS = 'STORAGE_SET_HELP_PRICELISTS';
export const STORAGE_HELP_PRICELISTS_ACTIVE = 'STORAGE_HELP_PRICELISTS_ACTIVE';

export const STORAGE_SET_HELP_PROJECTS = 'STORAGE_SET_HELP_PROJECTS';
export const STORAGE_HELP_PROJECTS_ACTIVE = 'STORAGE_HELP_PROJECTS_ACTIVE';

export const STORAGE_SET_HELP_STATUSES = 'STORAGE_SET_HELP_STATUSES';
export const STORAGE_HELP_STATUSES_ACTIVE = 'STORAGE_HELP_STATUSES_ACTIVE';

export const STORAGE_SET_HELP_TAGS = 'STORAGE_SET_HELP_TAGS';
export const STORAGE_HELP_TAGS_ACTIVE = 'STORAGE_HELP_TAGS_ACTIVE';

export const STORAGE_SET_HELP_TASK_TYPES = 'STORAGE_SET_HELP_TASK_TYPES';
export const STORAGE_HELP_TASK_TYPES_ACTIVE = 'STORAGE_HELP_TASK_TYPES_ACTIVE';

export const STORAGE_SET_HELP_TASKS = 'STORAGE_SET_HELP_TASKS';
export const STORAGE_HELP_TASKS_ACTIVE = 'STORAGE_HELP_TASKS_ACTIVE';

export const STORAGE_USERS = 'STORAGE_SET_USERS';
export const STORAGE_USERS_ACTIVE = 'STORAGE_USERS_ACTIVE';

//Filtering
export const SET_FILTER_PROJECT = 'SET_FILTER_PROJECT';
export const SET_FILTER_FILTER = 'SET_FILTER_FILTER';

// POD TYMTO BORDER

export const SET_SIDEBAR = 'SET_SIDEBAR';
export const SET_SIDEBAR_LOADING = 'SET_SIDEBAR_LOADING';


export const SET_USERS = 'SET_USERS';
export const SET_LOADING_USERS = 'SET_LOADING_USERS';
export const SET_LOADING_USER_ROLES = 'SET_LOADING_USER_ROLES';
export const SET_USER_ROLES = 'SET_USER_ROLES';
export const SET_USER_EMAIL_ERROR = 'SET_USER_EMAIL_ERROR';
export const SET_LOADING_USER = 'SET_LOADING_USER';
export const SET_USER = 'SET_USER';
export const EDIT_USER = 'EDIT_USER';

export const SET_COMPANIES = 'SET_COMPANIES';
export const SET_LOADING_COMPANIES = 'SET_LOADING_COMPANIES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const SET_LOADING_COMPANY = 'SET_LOADING_COMPANY';
export const SET_COMPANY = 'SET_COMPANY';
export const EDIT_COMPANY = 'EDIT_COMPANY';
export const SET_COMPANY_ATTRIBUTES_LOADING = 'SET_COMPANY_ATTRIBUTES_LOADING';
export const SET_COMPANY_ATTRIBUTES = 'SET_COMPANY_ATTRIBUTES';

export const SET_TASKS = 'SET_TASKS';
export const SET_LOADING_TASKS = 'SET_LOADING_TASKS';
export const SET_OPENED_ID = 'SET_OPENED_ID';
export const ADD_TASKS = 'ADD_TASKS';
export const SET_TASK_STATUSES_LOADING = 'SET_TASK_STATUSES_LOADING';
export const SET_TASK_STATUSES = 'SET_TASK_STATUSES';
export const SET_TASK_PROJECTS_LOADING = 'SET_TASK_PROJECTS_LOADING';
export const SET_TASK_PROJECTS = 'SET_TASK_PROJECTS';
export const SET_TASK_COMPANIES_LOADING = 'SET_TASK_COMPANIES_LOADING';
export const SET_TASK_COMPANIES = 'SET_TASK_COMPANIES';
export const SET_TASK_UNITS_LOADING = 'SET_TASK_UNITS_LOADING';
export const SET_TASK_UNITS = 'SET_TASK_UNITS';
export const SET_TASK_TAGS_LOADING = 'SET_TASK_TAGS_LOADING';
export const SET_TASK_TAGS = 'SET_TASK_TAGS';
export const SET_TASK_SOLVERS = 'SET_TASK_SOLVERS';
export const SET_TASK_LOADING = 'SET_TASK_LOADING';
export const SET_TASK = 'SET_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const SET_TASK_ATTRIBUTES_LOADING = 'SET_TASK_ATTRIBUTES_LOADING';
export const SET_TASK_ATTRIBUTES = 'SET_TASK_ATTRIBUTES';
export const SET_GENERAL_ORDER = 'SET_GENERAL_ORDER';

export const ADD_ATTACHMENT = 'ADD_ATTACHMENT';
export const EDIT_ATTACHMENT = 'EDIT_ATTACHMENT';
export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT';
export const CLEAR_ATTACHMENTS = 'CLEAR_ATTACHMENTS';

export const SET_ITEMS = 'SET_ITEMS';
export const SET_ITEMS_LOADING = 'SET_ITEMS_LOADING';
export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SET_UNITS_LOADING = 'SET_UNITS_LOADING';
export const SET_UNITS = 'SET_UNITS';

export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_AVATAR_URL = 'ADD_COMMENT_AVATAR_URL';
export const SET_COMMENT_ATTACHMENT = 'SET_COMMENT_ATTACHMENT';
export const SET_COMMENTS_LOADING = 'SET_COMMENTS_LOADING';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const SET_SUBTASKS = 'SET_SUBTASKS';
export const SET_SUBTASKS_LOADING = 'SET_SUBTASKS_LOADING';
export const ADD_SUBTASK = 'ADD_SUBTASK';
export const EDIT_SUBTASK = 'EDIT_SUBTASK';
export const DELETE_SUBTASK = 'DELETE_SUBTASK';
export const SET_SUBTASKS_COUNT = 'SET_SUBTASKS_COUNT';
export const ADD_TO_SUBTASKS_COUNT = 'ADD_TO_SUBTASKS_COUNT';
